server:
   port: 8081
   
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-product-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
  data:
    mongodb:
       uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DATABASE}   

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'