server:
   port: 8081
   
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-product-service
  data:
    mongodb:
       host: ${MONGO_DB_HOST}
       port: ${MONGO_DB_PORT}
       database: ${MONGO_DB_NAME}    

management:
  endpoints:
    web:
      exposure:
        include: "*"