spring:
  application:
    name: iss-product-service
  data:
    mongodb:
       host: localhost
       port: 27017
       database: MDB    

management:
  endpoints:
    web:
      exposure:
        include: "*"