server:
   port: 8081

springdoc:
  api-docs:
    path: /product-openapi
       
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-product-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'