server:
   port: 8081
   
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-product-service
  cloud:
    kubernetes:  
      discovery:
          enabled: false  
  data:
    mongodb:
       host: ${MONGO_DB_HOST}
       port: ${MONGO_DB_PORT}
       database: ${MONGO_DB_NAME}    

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'