server:
   port: 8081
   
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-product-service
  cloud:
    kubernetes:  
      discovery:
          enabled: false  
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'